name: Release
'on':
  push:
    branches:
      - master
      - next
      - beta
      - '*.x'
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.ANDOOK_GITHUB_BOT_PAT }}
          NPM_TOKEN: ${{ secrets.ANDOOK_GITHUB_BOT_NPM_TOKEN }}
